#!/usr/bin/env bash

# This utility is useful for exporting PI from EVEMon
# and estimating how much it costs using evepraisal.
#
# 1. In EVEMon open Planetary Industry tab
# 2. Right click -> Export To CSV...
# 3. Save it somewhere where this bash script can access
# 4. Provide file location as argument to this script
# 5. File will be changed. Paste it into https://evepraisal.com/
# 6. ...
# 7. Profit!
#
# EVEMon: https://evemondevteam.github.io/evemon/
# EVEPraisal: https://evepraisal.com/

set -xe

echo "$1"

if test -z "$1" ; then
    echo "No argument given! Please provide a csv file generated by EVEMon."
    return -1
fi

if ! test -e "$1" ; then
    echo "File [$1] does not exist!"
    return -1
fi

if ! test -r "$1" ; then
    echo "File [$1] is not readable!"
    return -1
fi

if ! test -s "$1" ; then
    echo "File [$1] is empty!"
    return -1
fi

if ! test -w "$1" ; then
    echo "File [$1] is not writeable!"
    return -1
fi

sed -re 's/^("[a-zA-Z0-9 :]*";){3}//' -e '/^"";.*/d' -e 's/;0;/ /' -e 's/"//g' -e 's/;.*//g
' -e '/[^0-9]$/d' -i "$1"

echo "File transformation complete! Open it and paste it into"
echo "https://evepraisal.com/"
